# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401, F403, F405

import builtins
import typing
__all__ = [
    "HpMocd",
    "ariadne",
    "ariadne_fronts",
    "ccm",
    "fitness",
    "hpmocd",
    "krm",
    "mmcomo",
    "mmcomo_fronts",
    "moga_net",
    "mocd_d",
    "mocd_q",
    "set_thread_count",
]

@typing.final
class HpMocd:
    r"""
    NSGA-II multi-objective community detection.
    
    Args:
        graph: networkx.Graph or DiGraph.
        debug_level: 0 silent, 1+ logs every 10 generations.
        pop_size: NSGA-II population size.
        num_gens: number of generations.
        cross_rate: crossover probability.
        mut_rate: mutation probability.
        objectives: optional list of callables ``(graph, partition) -> float``
            to minimise; replaces the built-in intra/inter objectives.
    """
    @property
    def num_gens(self) -> builtins.int:
        r"""
        Configured number of generations.
        """
    def __new__(cls, graph: typing.Any, debug_level: builtins.int = 0, pop_size: builtins.int = 100, num_gens: builtins.int = 100, cross_rate: builtins.float = 0.7, mut_rate: builtins.float = 0.5, objectives: typing.Optional[list] = None) -> HpMocd: ...
    def set_objectives(self, objectives: list) -> None:
        r"""
        Replace the objectives. Empty list reverts to built-in intra/inter.
        """
    def set_on_generation(self, callback: typing.Optional[typing.Any]) -> None:
        r"""
        Register per-generation callback ``(gen, num_gens, front_size) -> None``.
        Pass ``None`` to clear.
        """
    def generate_pareto_front(self) -> builtins.list[tuple[builtins.dict[builtins.int, builtins.int], builtins.list[builtins.float]]]:
        r"""
        Return all non-dominated solutions as ``[(partition, objectives), ...]``.
        Objective order matches the configured objectives (or intra/inter).
        """
    def run(self) -> builtins.dict[builtins.int, builtins.int]:
        r"""
        Run and return the best partition (max-Q from the Pareto front).
        Isolated nodes get community ``-1``.
        """

def ariadne(graph: typing.Any) -> builtins.dict[builtins.int, builtins.int]:
    r"""
    Run Ariadne — Adaptive Resolution Inference via Agreement-guided, Density-aware
    NSGA-II Evolution (dense-CSR NSGA-II, CPM objective) on ``graph``.

    The CPM resolution is chosen per-graph by the auto-γ heuristic; one
    migration-coupled NSGA-II island per γ is evolved, their rank-1 Pareto members
    (plus cohesion-guarded refined copies) form the frontier, and a label-free SBM
    minimum-description-length selector picks the single best member. There are no
    manual search parameters. Ariadne is crisp: exactly one community per node.

    Args:
        graph: networkx.Graph or igraph.Graph (integer node ids).

    Returns:
        ``dict[node, community]``. Isolated nodes get community ``-1``.
    """

def ariadne_fronts(graph: typing.Any) -> builtins.list[builtins.dict[builtins.int, builtins.int]]:
    r"""
    Return Ariadne's full frontier — the pooled rank-1 Pareto members across the
    predicted-γ islands plus refined copies, deduplicated. This is the candidate
    set that ``ariadne`` selects a single partition from (via the label-free SBM
    minimum-description-length selector); exposed for studying the selection step.
    """

def fitness(graph: typing.Any, partition: dict) -> builtins.float:
    r"""
    Modularity Q (Shi, 2012): ``Q = 1 - intra - inter``.
    """

def moga_net(graph: typing.Any, pop_size: builtins.int = 300, num_gens: builtins.int = 100, cross_rate: builtins.float = 0.8, mut_rate: builtins.float = 0.2, r: builtins.float = 2.0, alpha: builtins.float = 1.0) -> builtins.dict[builtins.int, builtins.int]:
    r"""
    Run MOGA-Net (Pizzuti 2012) — NSGA-II over the (Community Score, Community
    Fitness) bi-objective. Returns the max-modularity member of the rank-1 Pareto
    front. ``r`` is the Community Score power-mean exponent; ``alpha`` the
    Community Fitness exponent. Isolated nodes get community ``-1``.
    """

def mocd_q(graph: typing.Any, pop_size: builtins.int = 100, num_gens: builtins.int = 100, cross_rate: builtins.float = 0.9, mut_rate: builtins.float = 0.1) -> builtins.dict[builtins.int, builtins.int]:
    r"""
    Shi-MOCD with the Max-Q (MOCD-Q) selector (Shi et al. 2012, Eq. 3.8): the
    maximum-modularity member of the PESA-II Pareto front. Isolated nodes → ``-1``.
    """

def mocd_d(graph: typing.Any, pop_size: builtins.int = 100, num_gens: builtins.int = 100, cross_rate: builtins.float = 0.9, mut_rate: builtins.float = 0.1, rand_networks: builtins.int = 3) -> builtins.dict[builtins.int, builtins.int]:
    r"""
    Shi-MOCD with the Max-Min Distance (MOCD-D) selector (Shi et al. 2012, Eqs.
    3.9–3.11): the Pareto-front member deviating most from ``rand_networks``
    degree-preserving random control fronts. Isolated nodes → ``-1``.
    """

def ccm(graph: typing.Any, pop_size: builtins.int = 100, num_gens: builtins.int = 100, cross_rate: builtins.float = 0.8, mut_rate: builtins.float = 0.2, r: builtins.float = 1.0, alpha: builtins.float = 1.0, divisions: builtins.int = 12) -> builtins.dict[builtins.int, builtins.int]:
    r"""
    Run NSGA-III-CCM (Shaik, Ravi & Deb 2021) — NSGA-III over the three maximized
    objectives (Community Score, Community Fitness, Modularity). Returns the
    max-modularity member of the rank-1 Pareto front. ``r``/``alpha`` are the
    Community Score / Community Fitness exponents (Shaik default 1); ``divisions``
    is the Das–Dennis reference-point granularity. Isolated nodes → ``-1``.
    """

def krm(graph: typing.Any, pop_size: builtins.int = 100, num_gens: builtins.int = 100, cross_rate: builtins.float = 0.8, mut_rate: builtins.float = 0.2, divisions: builtins.int = 12) -> builtins.dict[builtins.int, builtins.int]:
    r"""
    Run NSGA-III-KRM (Shaik, Ravi & Deb 2021) — NSGA-III over (Kernel-K-Means,
    Ratio-Cut, Modularity); KKM & Ratio-Cut minimized, Modularity maximized.
    Returns the max-modularity member of the rank-1 Pareto front. ``divisions`` is
    the Das–Dennis reference-point granularity. Isolated nodes → ``-1``.
    """

def mmcomo(graph: typing.Any, pop_size: builtins.int = 100, num_gens: builtins.int = 50, cross_rate: builtins.float = 0.1, mut_rate: builtins.float = 0.1, gap: builtins.int = 10, beta: builtins.float = 0.05) -> builtins.dict[builtins.int, builtins.int]:
    r"""
    Run MMCoMO (Zhang, Yang, Yang & Zhang) — a macro-micro population-based
    co-evolutionary NSGA-II over (Kernel-K-Means, Ratio-Cut). A medoid-based macro
    population explores; a label-based micro population (modularity local search)
    exploits; they interact every ``gap`` generations via guidance/influence
    strategies coupled by a diffusion-kernel similarity matrix. Returns the
    max-modularity member of the merged rank-1 front. Isolated nodes → ``-1``.
    """

def mmcomo_fronts(graph: typing.Any, pop_size: builtins.int = 100, num_gens: builtins.int = 50, cross_rate: builtins.float = 0.1, mut_rate: builtins.float = 0.1, gap: builtins.int = 10, beta: builtins.float = 0.05) -> builtins.list[builtins.dict[builtins.int, builtins.int]]:
    r"""
    Return MMCoMO's full merged rank-1 Pareto front — the candidate set ``mmcomo``
    selects a single partition from. Isolated nodes → ``-1``.
    """

def hpmocd(graph: typing.Any) -> builtins.dict[builtins.int, builtins.int]:
    r"""
    Run HP-MOCD (NSGA-II) with defaults. For tuning, use the ``HpMocd`` class.

    Returns ``dict[node, community]``. Isolated nodes get ``-1``.
    """

def set_thread_count(num_threads: builtins.int) -> None:
    r"""
    Set Rayon's global thread count. First call wins; later calls are no-ops.
    """

